### ISSUE TITLE
conflicts with bootstrap3-Template (Giuseppe Di Terlizzi)

### ISSUE THREAD

**Issue by NikolausMB** [cosmocode/navi#13]
Using bootstrap3-template, an entry with hidden sub-entries has incorrect font-attributes.

Example: Entry "Tipps" has two sub-entries and is "closed"
![nav](https://cloud.githubusercontent.com/assets/1101285/17185131/188fb0fe-5430-11e6-8c7a-af906808f583.GIF)

-> incompatible definition of style ".close"

**Comment by natrius** [comment]
Same here, still happening. Sad, this Menustyle would be the best one imho.
