### ISSUE TITLE
Make use of icons instead of unordered list bullets to allow users to change that icons

### ISSUE THREAD

**Issue by benzolo** [cosmocode/navi#3]
It would be a great enhancement if the user could change the icons in the resulting menu from unordered list icons to something more intuitive like triangles that indicate that this is a group that can be opened. 
Something like this is done by the old outliner plugin or the indemenu plugin with the DokuWiki theme switched on. In the indexmenu plugin there are triangles that point to the right to show that this is a group to open. If the group is open there is a triangle oriantated towards the bottom to represent that state and to give a hint that pressing this symbol again will close the group again.

**Comment by splitbrain** [comment]
The wiki page has some addon code to do that https://www.dokuwiki.org/plugin:navi#addon

This code needs to be incorporated and possible bugs be fixed.
